jakarta.persistence.jdbc.driver=org.h2.Driver
jakarta.persistence.jdbc.url=jdbc:h2:./data/pr14db;AUTO_SERVER=TRUE
jakarta.persistence.jdbc.user=sa
jakarta.persistence.jdbc.password=

hibernate.dialect=org.hibernate.dialect.H2Dialect
hibernate.hbm2ddl.auto=create
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.highlight_sql=true